name: Generate and Update OpenAPI

on:
  pull_request:
    branches:
      - "*"

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path if needed

      - name: Run save_openapi_to_file
        id: save_openapi
        run: python scripts/generate_openapi.py

      #   - name: Run save_openapi_to_file
      #     id: save_openapi
      #     run: |
      #       if python -c "from sripts.generate_openapi import get_openapi_status; get_openapi_status()"; then
      #           echo "Changes detected"
      #           exit 1
      #       else
      #           echo "No changes detected"
      #           exit 0
      #       fi
      - name: Comment PR
        if: steps.save_openapi.outputs.changes_detected == '1'
        run: echo "here 1"
        # uses: thollander/actions-comment-pull-request@v2
        # with:
        #   message: |
        #     Chnages detected in openapi.json
        #   pr_number: ${{ github.event.number }}

      - name: test
        run: echo "testing"
