name: Generate and Update OpenAPI

on:
  pull_request:
    branches:
      - "*"

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path if needed

      - name: Run save_openapi_to_file
        run: |
          python -c "from src.main import save_openapi_to_file; save_openapi_to_file()"

      - name: Run save_openapi_to_file
        id: save_openapi
        run: |
          if python -c "from src.main import save_openapi_to_file; import sys; sys.exit(not save_openapi_to_file())"; then
              echo "Changes detected"
              exit 0
          else
              echo "No changes detected"
              exit 1
          fi

      - name: Comment PR
        if: steps.save_openapi.outputs.changes_detected == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Chnages detected in openapi.json
          pr_number: ${{ github.event.number }}

      - name: test
        run: echo "testing"
