name: Generate and Update OpenAPI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path if needed

      - name: Run save_openapi_to_file
        run: |
          python -c "from src.main import save_openapi_to_file; save_openapi_to_file()"

      - name: Check for Changes in openapi.json
        id: check_changes
        run: |
          # Get the commit SHA of the parent commit
          parent_commit=$(git rev-parse HEAD~1)

          # Check for changes in openapi.json between the parent commit and the current commit
          if [[ $(git diff --name-only $parent_commit ${{ github.sha }}) == *"openapi.json"* ]]; then
            echo "Changes detected in openapi.json"
          else
            echo "No changes detected in openapi.json"
            exit 1  # Exit with a non-zero code to indicate no changes
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.return-code == '0'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add openapi.json
          git commit -m "Update OpenAPI"
          git push origin HEAD:${{ github.head_ref }}
