name: Generate and Update OpenAPI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path if needed

      - name: Run save_openapi_to_file
        run: |
          python -c "from src.main import save_openapi_to_file; save_openapi_to_file()"

      - name: Compare OpenAPI files
        id: compare_openapi
        run: |
          # Compare the openapi.json in the main branch with the one in the pull request
          if ! git diff --exit-code origin/main:openapi.json openapi.json; then
            echo "Changes detected in openapi.json"
            echo "::set-output name=changes_detected::true"
          else
            echo "No changes detected in openapi.json"
            echo "::set-output name=changes_detected::false"
          fi

      - name: Comment on Pull Request
        if: steps.compare_openapi.outputs.changes_detected == 'true'
        run: |
          pr_number=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r ".[] | select(.head.sha == \"${{ github.sha }}\") | .number")
          comment_body="Changes detected in the \`openapi.json\` file."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -X POST -d "{\"body\":\"$comment_body\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments"
