name: Run smoke tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    services:
      fastapi:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
        ports:
          - 8000:80
        options: --name fastapi-app --entrypoint /start-reload.sh --env-file <(env | grep ^FASTAPI_) --volume "${{ github.workspace }}":/app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path if needed

      - name: Run FastAPI application
        run: uvicorn main:app --reload &

      - name: Wait for FastAPI to start
        run: sleep 5

      - name: Run Smoke Test
        run: scripts/smoke_test.sh
